//------------------------------------------------------------------------------
// <auto-generated>
//     Este código se generó a partir de una plantilla.
//
//     Los cambios manuales en este archivo pueden causar un comportamiento inesperado de la aplicación.
//     Los cambios manuales en este archivo se sobrescribirán si se regenera el código.
// </auto-generated>
//------------------------------------------------------------------------------

namespace Congelistos
{
    using System;
    using System.Collections.Generic;
    
    public partial class Pedido
    {
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2214:DoNotCallOverridableMethodsInConstructors")]
        public Pedido()
        {
            this.Detalle = new HashSet<Detalle>();
        }
    
        public int Id { get; set; }
        public System.DateTime Fecha_pedido { get; set; }
        public System.DateTime Fecha_entrega { get; set; }
        public decimal Total { get; set; }
        public bool Entregado { get; set; }
        public string Observaciones { get; set; }
        public int Id_Cliente { get; set; }
        public decimal SubTotal { get; set; }
        public Nullable<int> Descuento { get; set; }
    
        public virtual Cliente Cliente { get; set; }
        [System.Diagnostics.CodeAnalysis.SuppressMessage("Microsoft.Usage", "CA2227:CollectionPropertiesShouldBeReadOnly")]
        public virtual ICollection<Detalle> Detalle { get; set; }
    }
}
